[package]
name = "hello_world"
version = "1.0.0"
authors = ["eutro"]
edition = "2018"
autobins = false

[features]

[dependencies]
wasm-bindgen = "0.2.0"

[lib]
name = "hello_world"
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
