name: Javadoc

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Delete old docs
        run: rm -r ./docs

      - name: Run Javadoc
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc

      - name: Add and push
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "Automation"
          git add -v docs
          git commit -avm "Build Javadocs" && git push -v
